
# PlyParser_BoundaryDictParser_parsetab.py
# This file is automatically generated. Do not edit.

_lr_method = 'LALR'

_lr_signature = '-Lk3f\xb0\xdd\x1b\xba\xc5\xf8\x19\xfa\xbd\x06y'

_lr_action_items = {'NAME':([16,11,52,47,29,38,20,65,49,28,51,10,23,5,14,12,27,34,56,50,18,13,22,48,40,35,17,8,6,21,41,24,30,9,19,25,],[-19,-37,-15,-17,-30,-19,-20,-21,-14,-12,9,-38,21,9,-13,-33,-10,9,9,-16,-34,-32,-8,-29,-7,-18,9,-36,21,9,-5,-6,43,-31,-35,-9,]),')':([41,10,17,24,61,51,11,20,18,27,5,65,8,9,16,14,56,28,12,19,13,],[-5,-38,27,-6,63,-39,-37,-20,-34,-10,-39,-21,-36,-31,-19,-13,59,-12,-33,-35,-32,]),'(':([28,9,8,43,38,10,16,11,18,13,12,20,14,17,32,51,7,24,19,21,1,27,56,5,41,65,],[-12,-31,-36,5,51,-38,-19,-37,-34,-32,-33,-20,-13,5,44,5,-4,-6,-35,5,5,-10,5,5,-5,-21,]),'NONUNIFORM':([21,],[30,]),']':([64,16,20,],[65,-19,-20,]),'SCONST':([11,38,10,16,51,41,65,19,48,9,27,14,34,17,13,28,8,24,21,18,5,29,12,20,56,],[-37,-19,-38,-19,13,-5,-21,-35,-29,-31,-10,-13,13,13,-32,-12,-36,-6,13,-34,13,-30,-33,-20,13,]),'UNIFORM':([21,],[32,]),'FOAMFILE':([0,],[3,]),'ICONST':([9,34,65,16,10,21,26,32,8,28,19,29,20,17,38,18,42,44,58,60,24,41,5,11,48,15,57,51,55,13,53,14,56,62,12,27,],[-31,16,-21,-19,-38,38,16,16,-36,-12,-35,-30,-20,16,-19,-34,16,16,16,16,-6,-5,16,-37,-29,16,16,16,16,-32,16,-13,16,16,-33,-10,]),'{':([11,5,28,8,9,12,19,13,16,10,17,41,65,3,20,27,21,24,18,14,51,56,],[-37,6,-12,-36,-31,-33,-35,-32,-19,-38,6,-5,-21,6,-20,-10,6,-6,-34,-13,6,6,]),';':([12,39,36,37,21,54,45,18,65,20,27,16,48,9,31,59,29,38,19,13,33,63,34,46,],[-33,52,49,50,-39,-25,-23,-34,-21,-20,-10,-19,-28,-31,-26,-11,-27,-19,-35,-32,47,-22,-39,-24,]),'$end':([27,4,2,],[-10,-3,0,]),'}':([40,52,50,25,35,22,49,23,47,6,24,41,],[-7,-15,-16,-9,-18,-8,-14,41,-17,24,-6,-5,]),'[':([21,38,11,16,8,17,9,41,56,34,65,12,27,20,13,18,14,10,51,48,28,19,24,5,29,],[15,-19,-37,-19,-36,15,-31,-5,15,15,-21,-33,-10,-20,-32,-34,-13,-38,15,-29,-12,-35,-6,15,-30,]),'FCONST':([5,32,55,17,8,16,11,34,62,15,10,14,18,13,44,53,60,65,20,28,9,51,48,29,58,42,56,27,24,19,38,12,57,26,21,41,],[20,20,20,20,-36,-19,-37,20,20,20,-38,-13,-34,-32,20,20,20,-21,-20,-12,-31,20,-29,-30,20,20,20,-10,-6,-35,-19,-33,20,20,20,-5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       _lr_action[(_x,_k)] = _y
del _lr_action_items

_lr_goto_items = {'pitem':([34,5,51,56,21,17,],[48,8,8,8,29,8,]),'boundaryDict':([0,],[2,]),'pitemlist':([21,],[34,]),'dictline':([6,23,],[22,40,]),'dictionary':([51,56,5,21,17,3,],[10,10,10,35,10,7,]),'header':([0,],[1,]),'longitem':([21,],[31,]),'list':([1,17,21,43,51,5,56,],[4,11,39,54,11,11,11,]),'number':([15,21,32,5,55,44,56,62,58,60,34,42,17,57,26,53,51,],[26,12,45,12,58,55,12,64,61,62,12,53,12,60,42,57,12,]),'fieldvalue':([21,],[33,]),'prelist':([21,],[37,]),'item':([56,51,17,5,],[28,14,28,14,]),'vector':([32,],[46,]),'itemlist':([5,51,],[17,56,]),'dictitem':([21,],[36,]),'dictbody':([6,],[23,]),'dimension':([34,17,21,5,51,56,],[18,18,18,18,18,18,]),'empty':([5,6,56,17,34,21,51,],[19,25,19,19,19,19,19,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       _lr_goto[(_x,_k)] = _y
del _lr_goto_items
_lr_productions = [
  ("S'",1,None,None,None),
  ('global',2,'p_global','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',158),
  ('noHeader',1,'p_noHeader','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',162),
  ('boundaryDict',2,'p_boundaryDict','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',166),
  ('header',2,'p_header','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',171),
  ('dictionary',3,'p_dictionary','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',175),
  ('dictionary',2,'p_dictionary','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',176),
  ('dictbody',2,'p_dictbody','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',183),
  ('dictbody',1,'p_dictbody','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',184),
  ('dictbody',1,'p_dictbody','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',185),
  ('list',3,'p_list','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',197),
  ('prelist',4,'p_prelist','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',205),
  ('itemlist',2,'p_itemlist','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',209),
  ('itemlist',1,'p_itemlist','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',210),
  ('dictline',3,'p_dictline','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',221),
  ('dictline',3,'p_dictline','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',222),
  ('dictline',3,'p_dictline','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',223),
  ('dictline',3,'p_dictline','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',224),
  ('dictline',2,'p_dictline','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',225),
  ('number',1,'p_number','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',229),
  ('number',1,'p_number','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',230),
  ('dimension',9,'p_dimension','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',234),
  ('vector',5,'p_vector','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',238),
  ('fieldvalue',2,'p_fieldvalue_uniform','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',242),
  ('fieldvalue',2,'p_fieldvalue_uniform','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',243),
  ('fieldvalue',3,'p_fieldvalue_nonuniform','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',247),
  ('dictitem',1,'p_dictitem','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',251),
  ('dictitem',1,'p_dictitem','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',252),
  ('longitem',2,'p_longitem','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',256),
  ('pitemlist',2,'p_pitemlist','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',260),
  ('pitemlist',1,'p_pitemlist','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',261),
  ('pitem',1,'p_pitem','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',268),
  ('pitem',1,'p_pitem','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',269),
  ('pitem',1,'p_pitem','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',270),
  ('pitem',1,'p_pitem','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',271),
  ('pitem',1,'p_pitem','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',272),
  ('item',1,'p_item','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',276),
  ('item',1,'p_item','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',277),
  ('item',1,'p_item','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',278),
  ('empty',0,'p_empty','/Users/bgschaid/private_python/PyFoam/RunDictionary/ParsedParameterFile.py',282),
]
